--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ColinHDev/CPlotClaimAddon
build-by-default: true
branches:
- main
projects:
    CPlotClaimAddon:
        path: ""
        - src: sof3/await-generator/await-generator
          version: ^3.1.0
...
